spring:
  profiles:
    active:
    - dev

---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept-8001
    prefer-ip-address: true

info:
  app-name: microservicecloud
  company-name: www.nianzuochen.cn
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}